### ISSUE TITLE
You can create an extension like this for html file ??

### ISSUE THREAD

**Issue by kytosai** [ffpetrovic/scss-scope-helper#1]
Good extension.
You can create an extension like this for html file ??

Example:
```
<div class="a-block">
    <div class="b-segment c-segment">
          Content.....
    </div> // .b-segment .c-segment
</div>// .a-block
```

Thanks you !!!

**Comment by ffpetrovic** [comment]
Hi @KytoSai ,

I will look into it. If I ever do it or something similar, I will come back to this thread.
